export const PATH = {
  LOGIN: "/login",
  SETUP: "/",
  DASHBOARD: "/dashboard",
  USERS: "/master/users",
  USERS_PERMISSION: "/master/user_permission",

  SETTINGS: "/settings",
  CATEGORY: "/master/category",
  SUB_CATEGORY: "/master/sub-category",
  BRANCH: "/master/branch",
  ECONOMIC_YEAR: "/master/economic-year",
  SMS_SETTING: "/master/sms-setting",
  LEDGER: "/accounting/ledger",
  LEDGER_MAPPING: "/accounting/ledger-mapping",
  PATIENT: "master/patient",
  DOCTORLIST: "/doctor-list",
  PATIENTLIST: "master/patientlist",
  AGENTLIST: "master/agentlist",
  DOCTOR: "master/doctor",
  ACCOUNTING: "/accounting",
  VEHICLE_REGISTRATION: "/vehicle-registration",
  BILLING_TITLE: "/accounting/billing-title",
  BILLING_TITLE_MAPPING: "/accounting/billing-title-mapping",
  INVOICE: "/accounting/invoice",
  CASH_INVOICE: "/accounting/cashinvoice",
  REPORT: "/report",
  VEHICLE_EXPIRY_REPORT: "/report/vehicle-expiry-report",
  VEHICLE_RENEWAL_REPORT: "/report/renewal-reminder-report",
  INDIVIDUAL_LEDGER_REPORT: "/report/individual-ledger-report",
};
